### PR TITLE
Update PlotSquared dependency to v5

### PR DESCRIPTION
**Pull request by Wh1spr**
I thought I'd already do this, so simple merge for you 😉 
Completes #13

### CODE REVIEW

**Comment by Andre601** [comment]
What is with the case, where some people use older versions of PlotSquared because they can't/won't pay for the new Premium version?
Yes, I know you could compile it from source but still.

**Comment by bergerkiller** [comment]
Do I need to support both old and new versions of plotsquared, then? Very disappointed there is a premium/freemium split now with no cohesive API. I don't want to lock people in with a paid version like that. Can v5 at all be gotten the same way v4 can be?

**Comment by bergerkiller** [comment]
If the import <com.plotsquared.core.plot.Plot> works for everyone and won't leave me with people asking about broken support then I'm fine with merging this

**Comment by Andre601** [comment]
v5 is essentially the same (GitHub repo is the same) but it became [its own premium plugin on Spigot](https://www.spigotmc.org/resources/plotsquared-v5.77506/).
The API also changed in terms of path (From com.github.blablabla to com.plotsquared. Repository URL also seems to have changed).

v4 also found end of support with the release of v5 from what I know.

**Comment by bergerkiller** [comment]
Oh boy, the more I read into it the more I run into a massive amount of drama online hahaha. I'm not going to pick a side and look into supporting both v4 and v5 for the time being. If v5 ends up having unique features v4 doesn't have that people are willing to pay for, they are free to do so. Stopping support of v4 and trying to make money off of it is okay, but I don't like forcing this decision on other people in their name.

**Comment by Andre601** [comment]
While I am a person that encourages people to use the latest versions of server and plugins, do I think such a quick change without even announcing/warning people beforehand is not a good way.
Otherwise, people may get disappointed when they suddenly see errors, ask why this happens and then find out that v4 isn't supported anymore.
A way to still support it, but with the note that it gets removed in a later release is imo a good compromise between supporting the old, while also supporting the new.

**Comment by bergerkiller** [comment]
I've made some changes myself (basically duplicating the class and changing imports). If there's issues with these changes, please continue conversation in the issue ticket!

https://github.com/bergerhealer/TC-Coasters/commit/59aecf74647395d75bddf7af8b05e946dc351808

**Pull request closed without merging**
